version: "2"
run:
  tests: false
linters:
  default: all
  disable:
    - errcheck
    - mnd
    - depguard
    - err113
    - exhaustruct
    - varnamelen
    - forcetypeassert
    - perfsprint
    - revive
    - embeddedstructfieldcheck
    - wsl
    - tagliatelle
  settings:
    funlen:
      lines: 120
      statements: -1
      ignore-comments: true
